---
- name: Write GoBackup configuration file
  ansible.builtin.template:
    src: config.j2
    dest: "{{ gobackup_config_file_path }}"
    owner: root
    group: "{{ gobackup_system_group }}"
    mode: 0644
  notify:
    - restart gobackup

- name: Create GoBackup systemd service unit
  template:
    src: "service.j2"
    dest: "/etc/systemd/system/{{ gobackup }}.service"
    mode: 0644
  notify:
    - restart gobackup
