---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - gobackup_install
        - gobackup_configure
        - gobackup_run
  tags:
    - gobackup_install
    - gobackup_configure
    - gobackup_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - gobackup_install
  tags:
    - gobackup_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - gobackup_configure
  tags:
    - gobackup_configure

- name: Ensure GoBackup service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ gobackup_systemd_service }}"
    state: started
    enabled: true

- name: Flush handlers after run.
  ansible.builtin.meta: flush_handlers
